### ISSUE TITLE
GetResponseBody   bug

### ISSUE THREAD

**Issue by soulbird** [raff/godet#44]
panic: interface conversion: interface {} is nil, not string

goroutine 42 [running]:
github.com/raff/godet.(*RemoteDebugger).GetResponseBody(0xc04204c1e0, 0xc042493490, 0xd, 0x9, 0xc0434f4508, 0x0, 0x0, 0xc042c6de18)
        F:/Code/go_project/src/github.com/raff/godet/godet.go:897 +0x332
github.com/soulbird/elastic/chrome.(*Chrome).networkResponseReceived(0xc042090a00, 0xc0429f2810)
        F:/Code/go_project/src/github.com/soulbird/elastic/chrome/chrome.go:131 +0x566
github.com/soulbird/elastic/chrome.(*Chrome).(github.com/soulbird/elastic/chrome.networkResponseReceived)-fm(0xc0429f2810)
        F:/Code/go_project/src/github.com/soulbird/elastic/chrome/chrome.go:211 +0x3b
github.com/raff/godet.(*RemoteDebugger).processEvents(0xc04204c1e0)
        F:/Code/go_project/src/github.com/raff/godet/godet.go:531 +0x35b
created by github.com/raff/godet.Connect
        F:/Code/go_project/src/github.com/raff/godet/godet.go:252 +0x229

**Comment by soulbird** [comment]
It's usually easy to happen, Not related to the URL。 my code like this
main.go:
`
var wg sync.WaitGroup 

for clink := range w.cquenChan {  

    wg.Add(1)  

    go func(u url.URL) {  

        w.chrome.Fetch(u)  

        time.Sleep(time.Millisecond * 100)  

        wg.Done()  

    }(*clink)  

}  

wg.Wait()   
`
function Fetch

`
func (chrome *Chrome) Fetch(u url.URL) {
	remote := chrome.remote
	//remote.RuntimeEvents(true)
	remote.SetCacheDisabled(false)
	remote.NetworkEvents(true)
	remote.PageEvents(true)
	remote.DOMEvents(true)
	//remote.LogEvents(true)

	/*tab, err := remote.NewTab("about:blank")
	if err != nil {
		log.Println("create tab error:", err)
		return
	}
	defer remote.CloseTab(tab)*/
	// events needs to be associated to current tab (enable AFTER NewTab)
	remote.AllEvents(true)

	//var frameID string
	if chrome.proxyAddr != "" {
		dsnURL := strings.Replace(u.String(), u.Hostname(), chrome.proxyAddr, 1)

		remote.SetExtraHTTPHeaders(map[string]string{"host": u.Hostname()})
		_, err := remote.Navigate(dsnURL)
		if err != nil {
			log.Println("Navigate error:", err)
			return
		}
	} else {
		_, err := remote.Navigate(u.String())
		if err != nil {
			log.Println("Navigate error:", err)
			return
		}

	}
	remote.CallbackEvent("Network.responseReceived", chrome.networkResponseReceived)
}

`
